/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MDCReaderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MDC_EXTENSION = "mdc";
var MDCReaderPlugin = class extends import_obsidian.Plugin {
  onload() {
    this.registerExtensions([MDC_EXTENSION], "markdown");
    this.addRibbonIcon("file-text", "MDC file support", () => {
      new import_obsidian.Notice("MDC file support is active. You can now open .mdc files as Markdown.");
    });
    this.addCommand({
      id: "create-new-mdc-file",
      name: "Create new .mdc file",
      callback: async () => {
        await this.createNewMdcFile();
      }
    });
    this.addCommand({
      id: "convert-md-to-mdc",
      name: "Convert current .md file to .mdc",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && activeFile.extension === "md") {
          if (!checking) {
            void this.convertFile(activeFile, "md", "mdc");
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "convert-mdc-to-md",
      name: "Convert current .mdc file to .md",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && activeFile.extension === "mdc") {
          if (!checking) {
            void this.convertFile(activeFile, "mdc", "md");
          }
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "mdc") {
          menu.addItem((item) => {
            item.setTitle("Convert to .md").setIcon("file-text").onClick(async () => {
              await this.convertFile(file, "mdc", "md");
            });
          });
        }
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Convert to .mdc").setIcon("file-text").onClick(async () => {
              await this.convertFile(file, "md", "mdc");
            });
          });
        }
      })
    );
  }
  onunload() {
  }
  /**
   * Create a new .mdc file with a default template
   */
  async createNewMdcFile() {
    const defaultContent = `---
description: 
globs: 
alwaysApply: false
---

# New MDC Rule

`;
    try {
      const activeFile = this.app.workspace.getActiveFile();
      let folderPath = "";
      if (activeFile) {
        const parts = activeFile.path.split("/");
        parts.pop();
        folderPath = parts.join("/");
      }
      let fileName = "Untitled.mdc";
      let counter = 1;
      let fullPath = folderPath ? `${folderPath}/${fileName}` : fileName;
      while (this.app.vault.getAbstractFileByPath(fullPath)) {
        fileName = `Untitled ${counter}.mdc`;
        fullPath = folderPath ? `${folderPath}/${fileName}` : fileName;
        counter++;
      }
      const file = await this.app.vault.create(fullPath, defaultContent);
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
      new import_obsidian.Notice(`Created ${fileName}`);
    } catch (error) {
      console.error("Failed to create .mdc file:", error);
      new import_obsidian.Notice("Failed to create .mdc file.");
    }
  }
  /**
   * Convert a file from one extension to another by renaming it
   */
  async convertFile(file, fromExt, toExt) {
    try {
      const newPath = file.path.replace(new RegExp(`\\.${fromExt}$`), `.${toExt}`);
      if (this.app.vault.getAbstractFileByPath(newPath)) {
        new import_obsidian.Notice(`A file with the name ${newPath} already exists.`);
        return;
      }
      await this.app.fileManager.renameFile(file, newPath);
      new import_obsidian.Notice(`Converted ${file.name} to .${toExt}`);
    } catch (error) {
      console.error(`Failed to convert file:`, error);
      new import_obsidian.Notice(`Failed to convert file to .${toExt}`);
    }
  }
};
